### ISSUE TITLE
Unable to run turbo-eth (404) using yarn

### ISSUE THREAD

**Issue by arddluma** [turbo-eth/create-turbo-eth#17]
Having issues running turbo-eth due to not working URL.

➜  ~ yarn create turbo-eth              
yarn create v1.22.19
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error An unexpected error occurred: "https://codeload.github.com/hugomrdias/concat-stream/tar.gz/057bc7b5d6d8df26c8cf00a3f151b6721a0a8034: Request failed \"404 Not Found\"".

**Comment by marthendalnunes** [comment]
@arddluma fixed after v0.7.2 :D
